-- Calculates total revenue generated by each product.
-- Used to identify top-selling products and products contributing most to revenue.

SELECT
    product_name,
    CAST(ROUND(SUM(line_total), 2) AS DECIMAL(18,2)) AS revenue
FROM dbo.sales_analysis
GROUP BY product_name
ORDER BY revenue DESC;